/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultRouteImport } from './routes/result'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FormRouteImport } from './routes/form'
import { Route as CreateResumeRouteImport } from './routes/create-resume'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultIdRouteImport } from './routes/result.$id'

const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FormRoute = FormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateResumeRoute = CreateResumeRouteImport.update({
  id: '/create-resume',
  path: '/create-resume',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultIdRoute = ResultIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ResultRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-resume': typeof CreateResumeRoute
  '/form': typeof FormRoute
  '/history': typeof HistoryRoute
  '/result': typeof ResultRouteWithChildren
  '/result/$id': typeof ResultIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-resume': typeof CreateResumeRoute
  '/form': typeof FormRoute
  '/history': typeof HistoryRoute
  '/result': typeof ResultRouteWithChildren
  '/result/$id': typeof ResultIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-resume': typeof CreateResumeRoute
  '/form': typeof FormRoute
  '/history': typeof HistoryRoute
  '/result': typeof ResultRouteWithChildren
  '/result/$id': typeof ResultIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-resume'
    | '/form'
    | '/history'
    | '/result'
    | '/result/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-resume' | '/form' | '/history' | '/result' | '/result/$id'
  id:
    | '__root__'
    | '/'
    | '/create-resume'
    | '/form'
    | '/history'
    | '/result'
    | '/result/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateResumeRoute: typeof CreateResumeRoute
  FormRoute: typeof FormRoute
  HistoryRoute: typeof HistoryRoute
  ResultRoute: typeof ResultRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-resume': {
      id: '/create-resume'
      path: '/create-resume'
      fullPath: '/create-resume'
      preLoaderRoute: typeof CreateResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$id': {
      id: '/result/$id'
      path: '/$id'
      fullPath: '/result/$id'
      preLoaderRoute: typeof ResultIdRouteImport
      parentRoute: typeof ResultRoute
    }
  }
}

interface ResultRouteChildren {
  ResultIdRoute: typeof ResultIdRoute
}

const ResultRouteChildren: ResultRouteChildren = {
  ResultIdRoute: ResultIdRoute,
}

const ResultRouteWithChildren =
  ResultRoute._addFileChildren(ResultRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateResumeRoute: CreateResumeRoute,
  FormRoute: FormRoute,
  HistoryRoute: HistoryRoute,
  ResultRoute: ResultRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
